version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dbh'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'heidy'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'passwordh'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'passwordh'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: heidy
      PMA_PASSWORD: passwordh
    ports:
      - "8080:80"
# Names our volume
volumes:
  my-db: